### ISSUE TITLE
nice looking plugin but what about a plugin stylesheet?

### ISSUE THREAD

**Issue by bassauer-storms-media** [jackmparker/accordable.js#1]
the styles one needs are somewhere withunder the demo styles prefixed with IDs one perhaps won't have when using the plugin - is there a way of getting a stylesheet for the plugin only containing relevant styles without unnecessary prefix selectors?

**Comment by bassauer-storms-media** [comment]
PS. simple version of a stylesheet could perhaps look like this: https://pastebin.com/p5gnnHkk

**Comment by jackmparker** [comment]
I intentionally didn't provide any styles so you're able to make it look how you wish. I appreciate the suggestion but don't think I'll be adding a stylesheet at this time.
